name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
#      - name: Build with Maven
#        run: mvn clean install
      - name: Login dockerhub
        run: docker login -u hoangtheanh2002hhbg@gmail.com -p theanh.124_302
      - name: Info dockerhub
        run: docker info
      - name: Build image
        run: docker build -t hoangtheanh2002hhbg/projectmanagement:private .
      - name: Publish image
        run: docker push hoangtheanh2002hhbg/projectmanagement:private

  deploy:
    needs: build
    runs-on: theanh124
    steps:
      - name: Pull image
        run: sudo docker pull hoangtheanh2002hhbg/projectmanagement
      - name: Remove old container
        run: sudo docker rm -f projectmanagement-container
      - name: Run image
        run: sudo docker run -d -p 80:8080 --name projectmanagement-container -t hoangtheanh2002hhbg/projectmanagement
      - name: Logs
        run: sudo docker logs projectmanagement-container